stages:
  - build
  - test
  - best_practices
  - codequality

build:
  stage: build
  tags: ruby22
  script:
    - bundle install
    - bundle exec rake test_app

spec:
  stage: test
  script: 
   - rspec spec --seed 41689
  tags:
    - ruby22
  coverage: '/\(\d+.\d+\%\) covered/'

best_practices:
  stage: best_practices
  script:
    - rails_best_practices .
  tags:
    - ruby22

codequality:
  stage: codequality
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
      paths: [gl-code-quality-report.json]
  tags:
    - docker-concurrent
