stages:
  - test

before_script:
  - gem install bundle
  - bundle install
  - DB=mysql DB_PASSWORD='admin' bundle exec rake test_app

spec:services:
  stage: test
  script: 
   - rspec spec
  tags:
    - ruby22
  coverage: '/\(\d+.\d+\%\) covered/'
